### PR TITLE
Add platform.sh PHP settings when found

### PR DESCRIPTION
**Pull request by andriokha**
The file php.ini will be in the project root.

### CODE REVIEW

**Comment by dawehner** [comment]
Is there a place where we document which overrides are possible?

**Comment by dawehner** [comment]
Something like: You can use these files to override some of the configuration ....

**Comment by dawehner** [comment]
Anyway, I think this PR for itself looks totally cool.

**Comment by andriokha** [comment]
@dawehner yeah that's a good idea!

**Pull request merged**
